In [1]:
import pandas as pd
import geopandas as gpd
import GOSTnets as gn

In [2]:
%%time
limaamenities = pd.read_csv("LimaAmenities.csv")
gs = gpd.GeoSeries.from_wkt(limaamenities['geometry'])
limaamenities = gpd.GeoDataFrame(limaamenities, geometry=gs).set_index('osmid')
limaamenities.head()

<string>:2: DtypeWarning: Columns (5,6,7,11,12,13,14,16,17,18,19,20,21,23,24,25,26,27,29,30,31,34,43,44,45,46,47,48,49,50,51,52,53,54,55,59,60,61,62,63,64,65,66,67,68,69,70,71,72,74,75,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,103,104,105,106,107,108,109,110,111,112,114,115,116,117,118,119,120,121,122,123,124,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,254,255,256,257,258,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,287,288,289,290,291,292,293,295,296,299,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,322,323,324,325,326,327,328,329) have mixed types.Specify dtype option on import or set low_memory=False.

CPU times: user 1.7 s, sys: 287 ms, total: 1.99 s
Wall time: 1.99 s

,unique_id,element_type,amenity,geometry_polygon,fee,wheelchair,wheelchair:description,addr:city,addr:housenumber,addr:street,...,trolleybus,allotments,name:it,wikipedia:en,wikipedia:pl,wikipedia:sv,diesel,shortest_name,isPoint,geometry
osmid,,,,,,,,,,,,,,,,,,,,,
1706421372,node/1706421372,node,bus_station,POINT (-76.90808560000001 -12.2550125),NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,POINT (-76.90809 -12.25501)
1909452321,node/1909452321,node,toilets,POINT (-76.9071656 -12.2558628),no,no,No hay baño para silla de ruedas y encima tien...,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,POINT (-76.90717 -12.25586)
1932465988,node/1932465988,node,townhall,POINT (-76.7734648 -12.4016275),NaN,NaN,NaN,Santa María del Mar,100,El Sardinero,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,POINT (-76.77346 -12.40163)
2477708419,node/2477708419,node,restaurant,POINT (-76.8284223 -12.3324731),NaN,limited,Tiene baño para silla de ruedas y buena atencion,NaN,NaN,Calle Malecón Norte,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,POINT (-76.82842 -12.33247)
2477757589,node/2477757589,node,restaurant,POINT (-76.8235383 -12.3382439),NaN,limited,No se si tiene baño para silla de ruedas,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,POINT (-76.82354 -12.33824)

In [3]:
%%time
limanodes = pd.read_csv("LimaNodes.csv")
gs = gpd.GeoSeries.from_wkt(limanodes['geometry'])
limanodes = gpd.GeoDataFrame(limanodes, geometry=gs).set_index('osmid')
limanodes.head()

CPU times: user 1.94 s, sys: 29.1 ms, total: 1.97 s
Wall time: 1.97 s

,y,x,ref,highway,street_count,geometry
osmid,,,,,,
258066779,-12.371160,-76.784901,45A,motorway_junction,3,POINT (-76.78490 -12.37116)
258066780,-12.376522,-76.779354,NaN,NaN,3,POINT (-76.77935 -12.37652)
258066781,-12.384553,-76.771046,NaN,NaN,3,POINT (-76.77105 -12.38455)
258066783,-12.385783,-76.769768,NaN,NaN,3,POINT (-76.76977 -12.38578)
258067237,-12.304254,-76.840727,NaN,NaN,3,POINT (-76.84073 -12.30425)

In [4]:
%%time
# amenities_filter = ['bank','casino','clinic','courthouse','hospital','marketplace', 'police','school','university']
var = 'university'

cond = limaamenities['amenity'] == var
amenity = limaamenities[cond]
amenity.head()

CPU times: user 11.3 ms, sys: 0 ns, total: 11.3 ms
Wall time: 10.6 ms

,unique_id,element_type,amenity,geometry_polygon,fee,wheelchair,wheelchair:description,addr:city,addr:housenumber,addr:street,...,trolleybus,allotments,name:it,wikipedia:en,wikipedia:pl,wikipedia:sv,diesel,shortest_name,isPoint,geometry
osmid,,,,,,,,,,,,,,,,,,,,,
445592477,way/445592477,way,university,"POLYGON ((-76.8658868 -12.2357902, -76.8673503...",NaN,NaN,NaN,Pachacámac,NaN,Avenida Paul Poblet Lind,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,POINT (-76.86697 -12.23622)
445592484,way/445592484,way,university,"POLYGON ((-76.8627688 -12.2360693, -76.8635158...",NaN,NaN,NaN,Pachacámac,NaN,Avenida Riconada,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,POINT (-76.86269 -12.23828)
488970172,way/488970172,way,university,"POLYGON ((-76.90761430000001 -12.2211873, -76....",NaN,NaN,NaN,Villa María del Triunfo,NaN,Avenida Lima,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,POINT (-76.90751 -12.22128)
4408264590,node/4408264590,node,university,POINT (-76.8389263 -11.9880373),NaN,NaN,NaN,NaN,NaN,Calle Cusipata,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,POINT (-76.83893 -11.98804)
439814660,way/439814660,way,university,"POLYGON ((-76.91065140000001 -12.0231201, -76....",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,POINT (-76.91016 -12.02398)

In [5]:
%%time
# pandana = gn.pandana_snap_points( limanodes.head() , amenity.head() )
pandana = gn.pandana_snap_points( limanodes , amenity )

# pandana.head()

/home/leibnitz.rojas/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
/home/leibnitz.rojas/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:294: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  projstring = _prepare_from_string(" ".join((projstring, projkwargs)))
/home/leibnitz.rojas/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:53: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  return _prepare_from_string(" ".join(pjargs))
/home/leibnitz.rojas/.local/lib/python3.6/site-packages/pyproj/crs/crs.py:294: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  projstring = _prepare_from_string(" ".join((projstring, projkwargs)))

CPU times: user 3h 33min 18s, sys: 3min 30s, total: 3h 36min 48s
Wall time: 3h 36min 47s

In [6]:
%%time
# pandana.plot()
amenityid = "{}_osmid".format(var)
amenitydist = "{}_dist".format(var)
amenityid, amenitydist
pandana.rename(columns={'NN':amenityid, 'NN_dist': amenitydist}, inplace=True)
pandana.head()

CPU times: user 1.6 ms, sys: 0 ns, total: 1.6 ms
Wall time: 1.56 ms

,ref,highway,street_count,geometry,university_osmid,university_dist
osmid,,,,,,
258066779,45A,motorway_junction,3,POINT (-76.78490 -12.37116),445592484,0.153977
258066780,NaN,NaN,3,POINT (-76.77935 -12.37652),445592484,0.161420
258066781,NaN,NaN,3,POINT (-76.77105 -12.38455),445592484,0.172612
258066783,NaN,NaN,3,POINT (-76.76977 -12.38578),445592484,0.174333
258067237,NaN,NaN,3,POINT (-76.84073 -12.30425),445592484,0.069537

In [7]:
%%time
filename = "Lima{}.csv".format(var.capitalize())
filename
pandana.to_csv(filename)

CPU times: user 3.35 s, sys: 24 ms, total: 3.37 s
Wall time: 3.37 s